### ISSUE TITLE
Expecting specific answer sets

### ISSUE THREAD

**Issue by rkaminsk** [rndmcnlly/ansunit#2]
Hi Adam, what do you think about not just being able to test SAT, UNSAT, or OPTIMUM but test actual answer sets. To really know if a program is correct, I typically enumerate all answer sets and check them individually. Also checking that a problem has exactly n answer sets might be interesting. I could also imagine testing answer sets against a set of constraints. A bit like the REQUIRE(condition) directives you find in some testing frame works.

**Comment by rndmcnlly** [comment]
These are all good ideas, but I have some differing responses for each:

- Exactly n answer sets: In the past, I accomplished this with the current design by specifying a specific solution count on the command line and then checking for the OPTIMUM exit code. This isn't perfect, however, because resulting in fewer than expected solutions also passes the test. I don't have the time to update it now, but here's a design that I think would work: The "Expect" condition can be an object instead of a string. For example: "Expect: {Number: 5, Costs: [-12] }" Each key of the object is a conjunctive matching condition on JSON output. (This now requires the test to produce clean JSON output -- something not required before when I was just looking at return codes).

- Matching against a complete set of golden solutions: I have occasionally wanted this for myself in the past, but I decided not to support it directly in the test specification language. Instead, I wrote a small tool which would create a standalone yaml file from the visible outputs of an existing file. The reason for creating a separate file is that these golden solution set test are very brittle -- you often throw them out and regenerate them entirely rather than making small edits in the case of more focused tests. Perhaps a special mode of ansunit could create such a suite from all solutions to an existing test.

- Testing answer sets against a set of constraints: If the constraints are expressible in the modeling language already, they can be declared as an inline module (text in the .yaml file rather rather than a separate .lp file). If the constraints are some other extralogical Python condition to check, I can't quite imagine the use case right now to propose a design.

I'll keep these concerns in mind for the next time I do a project with ansunit (6 months?).
